### ISSUE TITLE
Problems compiling the module

### ISSUE THREAD

**Issue by themasch** [jdorner/node-sapnwrfc#10]
Hi, 

I get the following Error messages when I try to install the Module. 
I already copied the nwrfcsdk directory in the sapnwrfc module directory because he couldn't find the include file otherwise. 

```
C:\Project\Path\node_modules\sapnwrfc>npm i --python=python2

> sapnwrfc@0.1.5 install C:\Project\Path\node_modules\sapnwrfc
> node preinstall.js


C:\Project\Path\node_modules\sapnwrfc>node "C:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean
[Error: no errorC:\Project\Path\node_modules\sapnwrfc\compiled\0.10\win32\ia32\sapnwrfc.node]
error a precompiled module could not be found or loaded
info trying to compile it...

C:\Project\Path\node_modules\sapnwrfc>node "C:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  binding.cc
  Connection.cc
  Function.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. (..\src\Function.cc) [C:\Project\Path\node_modules\sapnwrfc\
build\sapnwrfc.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. (..\src\Connection.cc) [C:\Project\Path\node_modules\sapnwrf
c\build\sapnwrfc.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. (..\src\binding.cc) [C:\Project\Path\node_modules\sapnwrfc\b
uild\sapnwrfc.vcxproj]
..\src\Function.cc(538): warning C4018: '>': Konflikt zwischen 'signed' und 'unsigned' [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
..\src\Function.cc(561): warning C4018: '>': Konflikt zwischen 'signed' und 'unsigned' [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
..\src\Function.cc(584): warning C4018: '>': Konflikt zwischen 'signed' und 'unsigned' [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(1186,5): warning MSB8012: TargetPath(..\Release\sapnwrfc.node) does not match the Linker's OutputFile property value (C:\Project\Path\node_modules\sapnwrfc
\build\Release\sapnwrfc.node). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile). [C:\Users\schmale\workspace\UO Ec
o Base\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
     Bibliothek "C:\Project\Path\node_modules\sapnwrfc\build\Release\sapnwrfc.lib" und Objekt "C:\Project\Path\node_modules\sapnwrfc\build\Release\sapnwrfc.exp" werden erstellt.
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetVersion@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcIsConnectionHandleValid@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcPing@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcUTF8ToSAPUC@24". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcCloseConnection@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Connection.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcOpenConnection@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetTable@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcInvoke@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetRowCount@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcDescribeType@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetTime@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetFunctionDesc@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcMoveTo@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetStructure@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcCreateFunction@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetFieldCount@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetNum@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcDestroyFunction@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetParameterCount@12". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetString@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetBytes@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetInt@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetDate@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetBytes@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetInt1@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetChars@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetInt2@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetFloat@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetFloat@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetParameterDescByIndex@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetChars@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetInt1@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetFieldDescByIndex@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetStringLength@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetXString@24". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcAppendNewRow@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetDate@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetInt2@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetInt@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetParameterActive@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetCurrentRow@8". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetTime@16". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetString@24". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcGetNum@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Function.obj : error LNK2001: Nicht aufgel÷stes externes Symbol "_RfcSetXString@20". [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
Release\sapnwrfc.node : fatal error LNK1120: 45 nicht aufgel÷ste Externe [C:\Project\Path\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Chocolatey\\lib\\nodist.0.4.6-beta\\tools\\nodist-master\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Project\Path\node_modules\sapnwrfc
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by hikmettenis1** [comment]
did you resolve this issue? Im getting the same error

**Comment by Jeyakumarsv** [comment]
Hi Check your RFC SDK is right version or not
