### ISSUE TITLE
Problem installing sapnwrfc

### ISSUE THREAD

**Issue by franciscojgf** [jdorner/node-sapnwrfc#36]
Hi,
i'm having problem installing package sapnwrfc. 
I'm using: 
- Windows 10 pro, 
- node v8.9.3, 
- SAP NW RFC SDK 7.20.
The steps I have followed are:
1. download sap nw rfc sdk 7.20 from Sap support Portal
2. Decompress the file with SAPCAR (even this one downloaded from Sap Portal)
3. Copy the files in:   \nwrfcsdk\lib      to     c:\windows\System32
3. Create my project in C:\MY_PROJECT
4. In command prompt:  CD c:\my_project
5. run the command:  node install sapnwrfc. Then I have the error log below

I have tried some suggestions from other issues but without success. Can anyone, please, describe the right procedure? Thank you very much.
****************************************************************************************************
C:\my_project>npm install sapnwrfc

> sapnwrfc@0.2.0 install C:\my_project\node_modules\sapnwrfc
> node preinstall.js

C:\my_project\node_modules\sapnwrfc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
{ Error: Could not locate the bindings file. Tried:
 → C:\my_project\node_modules\sapnwrfc\build\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\build\Debug\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\build\Release\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\out\Debug\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\Debug\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\out\Release\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\Release\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\build\default\sapnwrfc.node
 → C:\my_project\node_modules\sapnwrfc\compiled\8.9\win32\x64\sapnwrfc.node
    at bindings (C:\my_project\node_modules\bindings\bindings.js:93:9)
    at ChildProcess.rebuild (C:\my_project\node_modules\sapnwrfc\preinstall.js:25:39)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  tries:
   [ 'C:\\my_project\\node_modules\\sapnwrfc\\build\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\build\\Debug\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\build\\Release\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\out\\Debug\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\Debug\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\out\\Release\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\Release\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\build\\default\\sapnwrfc.node',
     'C:\\my_project\\node_modules\\sapnwrfc\\compiled\\8.9\\win32\\x64\\sapnwrfc.node' ] }
error a precompiled module could not be found or loaded
info trying to compile it...

C:\my_project\node_modules\sapnwrfc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Francisco\Documents\JavaScript_PHP_Training\JavaScript\Python Software", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\my_project\node_modules\sapnwrfc
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN saveError ENOENT: no such file or directory, open 'C:\my_project\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\my_project\package.json'
npm WARN my_project No description
npm WARN my_project No repository field.
npm WARN my_project No README data
npm WARN my_project No license field.

+ sapnwrfc@0.2.0
added 3 packages in 2.116s

**Comment by iamraufu** [comment]
same
